CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(20) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(20) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Price" double precision NOT NULL,
    "Count" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

INSERT INTO "Categories" ("Id", "Name")
VALUES (1, 'Sausages');
INSERT INTO "Categories" ("Id", "Name")
VALUES (2, 'Steaks');
INSERT INTO "Categories" ("Id", "Name")
VALUES (3, 'Supplements');

INSERT INTO "Products" ("Id", "CategoryId", "Count", "Description", "Name", "Price")
VALUES (1, 1, 18, 'Handcrafted with care and expertise, offering a symphony of savory flavors and aromatic spices.', 'Bahay Kubo', 7.9900000000000002);
INSERT INTO "Products" ("Id", "CategoryId", "Count", "Description", "Name", "Price")
VALUES (2, 2, 4, 'A culinary masterpiece crafted to elevate your dining experience.', 'Kalabaw Rib', 49.990000000000002);
INSERT INTO "Products" ("Id", "CategoryId", "Count", "Description", "Name", "Price")
VALUES (3, 3, 41, 'Harness the potent properties of horn powder to support your overall health and vitality.', 'Horn Powder', 69.989999999999995);

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Products") + 1,
        nextval(pg_get_serial_sequence('"Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240410033432_InitialCreate', '8.0.4');


COMMIT;


