// <auto-generated />
using System;
using KalabawFoods.FrontEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KalabawFoods.FrontEnd.Migrations
{
    [DbContext(typeof(KalabawFoodsDbContext))]
    [Migration("20240410033432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KalabawFoods.FrontEnd.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sausages"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steaks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supplements"
                        });
                });

            modelBuilder.Entity("KalabawFoods.FrontEnd.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 18,
                            Description = "Handcrafted with care and expertise, offering a symphony of savory flavors and aromatic spices.",
                            Name = "Bahay Kubo",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Count = 4,
                            Description = "A culinary masterpiece crafted to elevate your dining experience.",
                            Name = "Kalabaw Rib",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Count = 41,
                            Description = "Harness the potent properties of horn powder to support your overall health and vitality.",
                            Name = "Horn Powder",
                            Price = 69.989999999999995
                        });
                });

            modelBuilder.Entity("KalabawFoods.FrontEnd.Data.Models.Product", b =>
                {
                    b.HasOne("KalabawFoods.FrontEnd.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KalabawFoods.FrontEnd.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
